-- ============================================================================
-- 01_schema.sql — KSP AI Investigation Copilot
-- Canonical Catalyst Data Store Schema
-- Revision: 2026-07-19
-- ============================================================================
-- IMPORTANT: Zoho Catalyst does NOT support DDL execution via SQL Editor.
--            Tables and columns MUST be created manually in the Catalyst Console.
--            This file is the authoritative reference for WHAT to create and
--            WHICH Catalyst Console type to select for each column.
--
-- Type Legend (Catalyst Console names only):
--   VarChar    — up to 255 chars. Supports Unique, Search Index, Default, Mandatory.
--   Text       — up to 10,000 chars. Supports Mandatory and PII/ePHI only.
--                *** NO Unique. NO Search Index on Text columns. ***
--   Int        — integer up to ~10 digits. Supports Unique, Mandatory, Search Index.
--   BigInt     — integer up to ~19 digits. Supports Unique, Mandatory, Search Index.
--   Double     — decimal/fractional. Supports Mandatory, Search Index. NO Unique.
--   Boolean    — true/false. Supports Default, Mandatory, Search Index.
--   Date       — YYYY-MM-DD. Supports Mandatory, Search Index.
--   DateTime   — YYYY-MM-DD HH:MM:SS. Supports Mandatory, Search Index.
--   Foreign Key — links to parent table. Supports Mandatory, Search Index.
--
-- ROWID is auto-generated by Catalyst for every table. Do NOT create it manually.
-- ============================================================================


-- ============================================================================
-- BLOCK 1: LOOKUP / REFERENCE TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table 1: CaseCategory
-- Purpose: Lookup — FIR filing type.
-- ----------------------------------------------------------------------------
CREATE TABLE CaseCategory (
    -- ROWID   BigInt   [auto-managed by Catalyst — do not create]
    id          Int             NOT NULL UNIQUE,
    name        VarChar(50)     NOT NULL UNIQUE
);
-- Catalyst Console properties:
--   id   : Int,      Mandatory=Yes, Unique=Yes
--   name : VarChar(50), Mandatory=Yes, Unique=Yes


-- ----------------------------------------------------------------------------
-- Table 2: GravityOffence
-- Purpose: Lookup — offence gravity level.
-- ----------------------------------------------------------------------------
CREATE TABLE GravityOffence (
    -- ROWID   BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    name        VarChar(50)     NOT NULL UNIQUE
);
-- Catalyst Console properties:
--   id   : Int,      Mandatory=Yes, Unique=Yes
--   name : VarChar(50), Mandatory=Yes, Unique=Yes


-- ----------------------------------------------------------------------------
-- Table 3: CrimeHead
-- Purpose: Lookup — major crime classification.
-- ----------------------------------------------------------------------------
CREATE TABLE CrimeHead (
    -- ROWID   BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    name        VarChar(100)    NOT NULL
);
-- Catalyst Console properties:
--   id   : Int,       Mandatory=Yes, Unique=Yes
--   name : VarChar(100), Mandatory=Yes


-- ----------------------------------------------------------------------------
-- Table 4: CrimeSubHead
-- Purpose: Lookup — crime sub-classification.
-- ----------------------------------------------------------------------------
CREATE TABLE CrimeSubHead (
    -- ROWID   BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    name        VarChar(100)    NOT NULL
);
-- Catalyst Console properties:
--   id   : Int,       Mandatory=Yes, Unique=Yes
--   name : VarChar(100), Mandatory=Yes


-- ----------------------------------------------------------------------------
-- Table 5: Unit
-- Purpose: Lookup — police station registry.
-- ----------------------------------------------------------------------------
CREATE TABLE Unit (
    -- ROWID    BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    name        VarChar(255)    NOT NULL,
    district    VarChar(100)    NOT NULL
);
-- Catalyst Console properties:
--   id       : Int,       Mandatory=Yes, Unique=Yes
--   name     : VarChar(255), Mandatory=Yes
--   district : VarChar(100), Mandatory=Yes


-- ----------------------------------------------------------------------------
-- Table 6: Employee
-- Purpose: Lookup — officer directory.
-- ----------------------------------------------------------------------------
CREATE TABLE Employee (
    -- ROWID       BigInt   [auto-managed by Catalyst]
    id              Int             NOT NULL UNIQUE,
    kgid            VarChar(20)     NOT NULL UNIQUE,   -- SearchIndex=Yes
    firstName       VarChar(100)    NOT NULL,
    lastName        VarChar(100)    NOT NULL,
    rank            VarChar(100)    NOT NULL,
    designation     VarChar(100)    NOT NULL
);
-- Catalyst Console properties:
--   id          : Int,        Mandatory=Yes, Unique=Yes
--   kgid        : VarChar(20), Mandatory=Yes, Unique=Yes, Search Index=Yes
--   firstName   : VarChar(100), Mandatory=Yes
--   lastName    : VarChar(100), Mandatory=Yes
--   rank        : VarChar(100), Mandatory=Yes
--   designation : VarChar(100), Mandatory=Yes


-- ============================================================================
-- BLOCK 2: TRANSACTIONAL CORE TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table 7: CaseMaster
-- Purpose: Primary FIR and case registration records.
-- ----------------------------------------------------------------------------
CREATE TABLE CaseMaster (
    -- ROWID               BigInt   [auto-managed by Catalyst]
    id                      Int             NOT NULL UNIQUE,
    crimeNo                 VarChar(50)     NOT NULL UNIQUE,   -- SearchIndex=Yes
    caseNo                  VarChar(20)     NOT NULL,
    crimeRegisteredDate     DateTime        NOT NULL,
    policePersonId          Foreign Key (Employee),            -- Mandatory=Yes, SearchIndex=Yes
    policeStationId         Foreign Key (Unit),                -- Mandatory=Yes
    caseCategoryId          Foreign Key (CaseCategory),        -- Mandatory=Yes
    gravityOffenceId        Foreign Key (GravityOffence),      -- Mandatory=Yes
    crimeMajorHeadId        Foreign Key (CrimeHead),           -- Mandatory=Yes
    crimeMinorHeadId        Foreign Key (CrimeSubHead),        -- Mandatory=Yes
    caseStatus              VarChar(30)     NOT NULL,          -- SearchIndex=Yes
    casePriority            VarChar(10)     NOT NULL,
    briefFacts              Text            NOT NULL,
    incidentFromDate        DateTime        NOT NULL,
    incidentToDate          DateTime        NOT NULL,
    infoReceivedPSDate      DateTime        NOT NULL,
    latitude                Double          NOT NULL,
    longitude               Double          NOT NULL,
    createdAt               DateTime        NOT NULL,
    updatedAt               DateTime        NOT NULL
);
-- Catalyst Console properties:
--   id                  : Int,        Mandatory=Yes, Unique=Yes
--   crimeNo             : VarChar(50), Mandatory=Yes, Unique=Yes, Search Index=Yes
--   caseNo              : VarChar(20), Mandatory=Yes
--   crimeRegisteredDate : DateTime,    Mandatory=Yes
--   policePersonId      : Foreign Key → Employee, Mandatory=Yes, Search Index=Yes
--   policeStationId     : Foreign Key → Unit, Mandatory=Yes
--   caseCategoryId      : Foreign Key → CaseCategory, Mandatory=Yes
--   gravityOffenceId    : Foreign Key → GravityOffence, Mandatory=Yes
--   crimeMajorHeadId    : Foreign Key → CrimeHead, Mandatory=Yes
--   crimeMinorHeadId    : Foreign Key → CrimeSubHead, Mandatory=Yes
--   caseStatus          : VarChar(30), Mandatory=Yes, Search Index=Yes
--                         Enum values: UNDER_INVESTIGATION | CHARGE_SHEETED | CLOSED | ARCHIVED
--   casePriority        : VarChar(10), Mandatory=Yes
--                         Enum values: HIGH | MEDIUM | LOW
--   briefFacts          : Text, Mandatory=Yes  [NOTE: Text — no Unique/Search Index]
--   incidentFromDate    : DateTime, Mandatory=Yes
--   incidentToDate      : DateTime, Mandatory=Yes
--   infoReceivedPSDate  : DateTime, Mandatory=Yes
--   latitude            : Double, Mandatory=Yes  [Karnataka bounds: 11.0–19.0]
--   longitude           : Double, Mandatory=Yes  [Karnataka bounds: 74.0–79.0]
--   createdAt           : DateTime, Mandatory=Yes
--   updatedAt           : DateTime, Mandatory=Yes


-- ----------------------------------------------------------------------------
-- Table 8: Victim
-- Purpose: Victim/complainant records per case.
-- ----------------------------------------------------------------------------
CREATE TABLE Victim (
    -- ROWID    BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    caseId      Foreign Key (CaseMaster),           -- Mandatory=Yes, SearchIndex=Yes
    name        VarChar(255)    NOT NULL,
    age         Int             NOT NULL,
    contact     VarChar(50),
    description Text,
    injuryType  VarChar(50)
);
-- Catalyst Console properties:
--   id          : Int,        Mandatory=Yes, Unique=Yes
--   caseId      : Foreign Key → CaseMaster, Mandatory=Yes, Search Index=Yes
--   name        : VarChar(255), Mandatory=Yes
--   age         : Int,        Mandatory=Yes
--   contact     : VarChar(50), Mandatory=No
--   description : Text,       Mandatory=No  [PII=Yes]
--   injuryType  : VarChar(50), Mandatory=No
--                 Enum values: None | Minor | Grievous | Fatal


-- ----------------------------------------------------------------------------
-- Table 9: Suspect
-- Purpose: Suspect/accused records per case.
-- ----------------------------------------------------------------------------
CREATE TABLE Suspect (
    -- ROWID    BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    caseId      Foreign Key (CaseMaster),           -- Mandatory=Yes, SearchIndex=Yes
    name        VarChar(255)    NOT NULL,
    age         Int             NOT NULL,
    contact     VarChar(50),
    description Text,
    status      VarChar(30)     NOT NULL             -- SearchIndex=Yes
);
-- Catalyst Console properties:
--   id          : Int,        Mandatory=Yes, Unique=Yes
--   caseId      : Foreign Key → CaseMaster, Mandatory=Yes, Search Index=Yes
--   name        : VarChar(255), Mandatory=Yes
--   age         : Int,        Mandatory=Yes  [0 = unknown]
--   contact     : VarChar(50), Mandatory=No
--   description : Text,       Mandatory=No  [PII=Yes]
--   status      : VarChar(30), Mandatory=Yes, Search Index=Yes
--                 Enum values: ABSCONDING | UNDER_CUSTODY | SUSPECTED | INTERROGATED


-- ----------------------------------------------------------------------------
-- Table 10: InvestigationNote
-- Purpose: Case investigation journal. Soft-delete only — no physical DELETE.
-- ----------------------------------------------------------------------------
CREATE TABLE InvestigationNote (
    -- ROWID            BigInt   [auto-managed by Catalyst]
    id                  Int             NOT NULL UNIQUE,
    caseId              Foreign Key (CaseMaster),           -- Mandatory=Yes, SearchIndex=Yes
    content             Text            NOT NULL,
    createdBy           VarChar(255)    NOT NULL,
    createdKgid         VarChar(20)     NOT NULL,
    createdAt           DateTime        NOT NULL,
    updatedAt           DateTime        NOT NULL,
    lastModifiedBy      VarChar(255),
    lastModifiedKgid    VarChar(20),
    isDeleted           Boolean         NOT NULL DEFAULT FALSE  -- SearchIndex=Yes
);
-- Catalyst Console properties:
--   id               : Int,        Mandatory=Yes, Unique=Yes
--   caseId           : Foreign Key → CaseMaster, Mandatory=Yes, Search Index=Yes
--   content          : Text,       Mandatory=Yes  [NOTE: no Unique/Search Index]
--   createdBy        : VarChar(255), Mandatory=Yes
--   createdKgid      : VarChar(20), Mandatory=Yes
--   createdAt        : DateTime,   Mandatory=Yes
--   updatedAt        : DateTime,   Mandatory=Yes
--   lastModifiedBy   : VarChar(255), Mandatory=No
--   lastModifiedKgid : VarChar(20), Mandatory=No
--   isDeleted        : Boolean,    Mandatory=Yes, Default=false, Search Index=Yes
-- CONSTRAINT: No DELETE operations. Set isDeleted=true to archive.


-- ----------------------------------------------------------------------------
-- Table 11: EvidenceMaster
-- Purpose: Forensic asset registry.
-- ----------------------------------------------------------------------------
CREATE TABLE EvidenceMaster (
    -- ROWID            BigInt   [auto-managed by Catalyst]
    id                  Int             NOT NULL UNIQUE,
    evidenceNo          VarChar(30)     NOT NULL UNIQUE,    -- SearchIndex=Yes
    caseId              Foreign Key (CaseMaster),           -- Mandatory=Yes, SearchIndex=Yes
    crimeNo             VarChar(50)     NOT NULL,
    title               VarChar(255)    NOT NULL,
    description         Text            NOT NULL,
    evidenceType        VarChar(20)     NOT NULL,
    status              VarChar(30)     NOT NULL,           -- SearchIndex=Yes
    collectionDate      Date            NOT NULL,
    collectionTime      VarChar(10)     NOT NULL,
    latitude            Double          NOT NULL,
    longitude           Double          NOT NULL,
    collectorName       VarChar(255)    NOT NULL,
    collectorKgid       VarChar(20)     NOT NULL,           -- SearchIndex=Yes
    fileHash            VarChar(100)    NOT NULL,
    fileSize            BigInt          NOT NULL,
    mimeType            VarChar(100)    NOT NULL,
    fileName            VarChar(255)    NOT NULL,
    tags                Text,
    ocrText             Text,
    aiLabels            Text,
    analysisSummary     Text,
    extractedEntities   Text,
    createdAt           DateTime        NOT NULL,
    updatedAt           DateTime        NOT NULL
);
-- Catalyst Console properties:
--   id                : Int,        Mandatory=Yes, Unique=Yes
--   evidenceNo        : VarChar(30), Mandatory=Yes, Unique=Yes, Search Index=Yes
--                       Pattern: EV-YYYY-NNNNNN
--   caseId            : Foreign Key → CaseMaster, Mandatory=Yes, Search Index=Yes
--   crimeNo           : VarChar(50), Mandatory=Yes  [denormalized for search]
--   title             : VarChar(255), Mandatory=Yes
--   description       : Text,       Mandatory=Yes
--   evidenceType      : VarChar(20), Mandatory=Yes
--                       Enum: PHYSICAL | DIGITAL | DOCUMENT | IMAGE | VIDEO | AUDIO | DEVICE
--   status            : VarChar(30), Mandatory=Yes, Search Index=Yes
--                       Enum: SECURED | IN_TRANSIT | RELEASED | SUBMITTED_TO_COURT | ARCHIVED
--   collectionDate    : Date,       Mandatory=Yes
--   collectionTime    : VarChar(10), Mandatory=Yes  [format: HH:MM]
--   latitude          : Double,     Mandatory=Yes  [Karnataka bounds: 11.0–19.0]
--   longitude         : Double,     Mandatory=Yes  [Karnataka bounds: 74.0–79.0]
--   collectorName     : VarChar(255), Mandatory=Yes
--   collectorKgid     : VarChar(20), Mandatory=Yes, Search Index=Yes
--   fileHash          : VarChar(100), Mandatory=Yes  [SHA-256 checksum]
--   fileSize          : BigInt,     Mandatory=Yes  [bytes; 0 for physical assets]
--   mimeType          : VarChar(100), Mandatory=Yes
--   fileName          : VarChar(255), Mandatory=Yes
--   tags              : Text,       Mandatory=No   [serialized JSON string[]]
--   ocrText           : Text,       Mandatory=No   [raw OCR output]
--   aiLabels          : Text,       Mandatory=No   [serialized JSON string[]]
--   analysisSummary   : Text,       Mandatory=No
--   extractedEntities : Text,       Mandatory=No   [serialized JSON Record<string,string[]>]
--   createdAt         : DateTime,   Mandatory=Yes
--   updatedAt         : DateTime,   Mandatory=Yes


-- ----------------------------------------------------------------------------
-- Table 12: CustodyEvent
-- Purpose: Append-only chain-of-custody event log. INSERT only — no UPDATE/DELETE.
-- ----------------------------------------------------------------------------
CREATE TABLE CustodyEvent (
    -- ROWID        BigInt   [auto-managed by Catalyst]
    id              Int             NOT NULL UNIQUE,
    evidenceId      Foreign Key (EvidenceMaster),       -- Mandatory=Yes, SearchIndex=Yes
    eventTimestamp  DateTime        NOT NULL,
    officerName     VarChar(255)    NOT NULL,
    officerKgid     VarChar(20)     NOT NULL,
    action          VarChar(30)     NOT NULL,
    previousState   VarChar(100)    NOT NULL,
    currentState    VarChar(100)    NOT NULL,
    remarks         Text            NOT NULL
);
-- Catalyst Console properties:
--   id            : Int,        Mandatory=Yes, Unique=Yes
--   evidenceId    : Foreign Key → EvidenceMaster, Mandatory=Yes, Search Index=Yes
--   eventTimestamp: DateTime,   Mandatory=Yes
--   officerName   : VarChar(255), Mandatory=Yes
--   officerKgid   : VarChar(20), Mandatory=Yes
--   action        : VarChar(30), Mandatory=Yes
--                   Enum: REGISTERED | TRANSFERRED | STATUS_CHANGED | TAGGED | ARCHIVED | AI_CLASSIFICATION
--   previousState : VarChar(100), Mandatory=Yes  [use 'None' for first entry]
--   currentState  : VarChar(100), Mandatory=Yes
--   remarks       : Text,       Mandatory=Yes
-- CONSTRAINT: INSERT only. No UPDATE or DELETE.


-- ============================================================================
-- BLOCK 3: AI INTELLIGENCE & ANNOTATION TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table 13: IntelligenceRecord
-- Purpose: Versioned AI analysis records per evidence asset.
-- ----------------------------------------------------------------------------
CREATE TABLE IntelligenceRecord (
    -- ROWID            BigInt   [auto-managed by Catalyst]
    id                  VarChar(50)     NOT NULL UNIQUE,   -- UUID
    evidenceId          Foreign Key (EvidenceMaster),      -- Mandatory=Yes, SearchIndex=Yes
    version             Int             NOT NULL,
    analyzedAt          DateTime        NOT NULL,
    ocrRawText          Text            NOT NULL,
    ocrConfidence       Double          NOT NULL,
    ocrProvider         VarChar(100)    NOT NULL,
    analysisSummary     Text            NOT NULL,
    aiLabels            Text            NOT NULL,          -- serialized JSON string[]
    overallConfidence   Double          NOT NULL,
    provider            VarChar(100)    NOT NULL,
    relationships       Text                               -- serialized JSON EntityRelationship[]
);
-- Catalyst Console properties:
--   id                : VarChar(50), Mandatory=Yes, Unique=Yes  [UUID]
--   evidenceId        : Foreign Key → EvidenceMaster, Mandatory=Yes, Search Index=Yes
--   version           : Int,        Mandatory=Yes  [monotonically increasing per evidence]
--   analyzedAt        : DateTime,   Mandatory=Yes  [maps to OcrResult.processedAt in TypeScript]
--   ocrRawText        : Text,       Mandatory=Yes  [maps to OcrResult.rawText]
--   ocrConfidence     : Double,     Mandatory=Yes  [range: 0.0–1.0; maps to OcrResult.confidence]
--   ocrProvider       : VarChar(100), Mandatory=Yes [maps to OcrResult.provider]
--   analysisSummary   : Text,       Mandatory=Yes
--   aiLabels          : Text,       Mandatory=Yes  [serialized JSON string[]]
--   overallConfidence : Double,     Mandatory=Yes  [range: 0.0–1.0]
--   provider          : VarChar(100), Mandatory=Yes
--   relationships     : Text,       Mandatory=No   [serialized JSON EntityRelationship[]]


-- ----------------------------------------------------------------------------
-- Table 14: ExtractedEntity
-- Purpose: Named entities from OCR/NLP pipelines.
-- NOTE: 'value' field uses Text (not VarChar) because entity values can exceed 255 chars.
-- ----------------------------------------------------------------------------
CREATE TABLE ExtractedEntity (
    -- ROWID                BigInt   [auto-managed by Catalyst]
    id                      VarChar(50)     NOT NULL UNIQUE,   -- stable UUID
    intelligenceRecordId    Foreign Key (IntelligenceRecord),  -- Mandatory=Yes, SearchIndex=Yes
    sourceEvidenceId        Foreign Key (EvidenceMaster),      -- Mandatory=Yes
    value                   Text            NOT NULL,          -- can exceed 255 chars
    type                    VarChar(30)     NOT NULL,
    confidence              Double          NOT NULL,
    extractionMethod        VarChar(50)     NOT NULL,
    extractedAt             DateTime        NOT NULL,
    reviewStatus            VarChar(20)     NOT NULL DEFAULT 'PENDING'  -- SearchIndex=Yes
);
-- Catalyst Console properties:
--   id                   : VarChar(50), Mandatory=Yes, Unique=Yes  [stable UUID]
--   intelligenceRecordId : Foreign Key → IntelligenceRecord, Mandatory=Yes, Search Index=Yes
--   sourceEvidenceId     : Foreign Key → EvidenceMaster, Mandatory=Yes
--   value                : Text,       Mandatory=Yes  [NOTE: Text not VarChar — values can exceed 255 chars]
--   type                 : VarChar(30), Mandatory=Yes
--                          Enum: PERSON | PHONE | VEHICLE | ADDRESS | EMAIL |
--                                ORGANIZATION | DATE | TIME | CURRENCY | IDENTITY_NUMBER
--   confidence           : Double,     Mandatory=Yes  [range: 0.0–1.0]
--   extractionMethod     : VarChar(50), Mandatory=Yes
--                          Values: REGEX_PATTERN | ZIA_NLP | QUICKML_LLM
--   extractedAt          : DateTime,   Mandatory=Yes
--   reviewStatus         : VarChar(20), Mandatory=Yes, Default='PENDING', Search Index=Yes
--                          Enum: PENDING | ACCEPTED | REJECTED


-- ----------------------------------------------------------------------------
-- Table 15: ReviewEvent
-- Purpose: Immutable audit log of officer review decisions. INSERT only.
-- ----------------------------------------------------------------------------
CREATE TABLE ReviewEvent (
    -- ROWID        BigInt   [auto-managed by Catalyst]
    id              VarChar(50)     NOT NULL UNIQUE,   -- UUID
    entityId        Foreign Key (ExtractedEntity),     -- Mandatory=Yes, SearchIndex=Yes
    evidenceId      Foreign Key (EvidenceMaster),      -- Mandatory=Yes
    officerKgid     VarChar(20)     NOT NULL,
    officerName     VarChar(255)    NOT NULL,
    action          VarChar(30)     NOT NULL,
    previousStatus  VarChar(20)     NOT NULL,
    newStatus       VarChar(20)     NOT NULL,
    eventTimestamp  DateTime        NOT NULL
);
-- Catalyst Console properties:
--   id             : VarChar(50), Mandatory=Yes, Unique=Yes  [UUID]
--   entityId       : Foreign Key → ExtractedEntity, Mandatory=Yes, Search Index=Yes
--   evidenceId     : Foreign Key → EvidenceMaster, Mandatory=Yes
--   officerKgid    : VarChar(20), Mandatory=Yes
--   officerName    : VarChar(255), Mandatory=Yes
--   action         : VarChar(30), Mandatory=Yes
--                    Enum: ACCEPTED | REJECTED | RESET_TO_PENDING
--   previousStatus : VarChar(20), Mandatory=Yes
--   newStatus      : VarChar(20), Mandatory=Yes
--   eventTimestamp : DateTime,   Mandatory=Yes
-- CONSTRAINT: INSERT only. No UPDATE or DELETE.


-- ----------------------------------------------------------------------------
-- Table 16: ActivityLog
-- Purpose: Immutable case-level system audit trail. INSERT only.
-- ----------------------------------------------------------------------------
CREATE TABLE ActivityLog (
    -- ROWID    BigInt   [auto-managed by Catalyst]
    id          Int             NOT NULL UNIQUE,
    caseId      Foreign Key (CaseMaster),       -- Mandatory=Yes, SearchIndex=Yes
    crimeNo     VarChar(50)     NOT NULL,
    caseNo      VarChar(20)     NOT NULL,
    officerName VarChar(255)    NOT NULL,
    action      VarChar(30)     NOT NULL,
    eventTimestamp DateTime        NOT NULL
);
-- Catalyst Console properties:
--   id          : Int,        Mandatory=Yes, Unique=Yes
--   caseId      : Foreign Key → CaseMaster, Mandatory=Yes, Search Index=Yes
--   crimeNo     : VarChar(50), Mandatory=Yes  [denormalized]
--   caseNo      : VarChar(20), Mandatory=Yes  [denormalized]
--   officerName : VarChar(255), Mandatory=Yes
--   action      : VarChar(30), Mandatory=Yes
--                 Enum: CREATED | UPDATED | STATUS_CHANGED | ARCHIVED |
--                       NOTE_ADDED | NOTE_EDITED | NOTE_DELETED
--   eventTimestamp: DateTime,   Mandatory=Yes
-- CONSTRAINT: INSERT only. No UPDATE or DELETE.


-- ============================================================================
-- INDEXES
-- (Configure these in Catalyst Console → Table → Column → Search Index)
-- ============================================================================
-- CaseMaster   : crimeNo (unique), caseStatus, policePersonId
-- Victim       : caseId
-- Suspect      : caseId, status
-- InvestigationNote : caseId, isDeleted
-- EvidenceMaster    : evidenceNo (unique), caseId, status, collectorKgid
-- CustodyEvent      : evidenceId
-- IntelligenceRecord: evidenceId
-- ExtractedEntity   : intelligenceRecordId, reviewStatus
-- ReviewEvent       : entityId
-- ActivityLog       : caseId
